Repository mizdra/happy-css-modules, pull requests merged in 2024-05, with the labels that each got.

#241 Fix CI
  .vscode/settings.json
  eslint.config.js
  jest.setup.ts
  package-lock.json
  package.json
  packages/happy-css-modules/src/emitter/dts.test.ts
  packages/happy-css-modules/src/emitter/dts.ts
  packages/happy-css-modules/src/emitter/index.ts
  packages/happy-css-modules/src/emitter/source-map.test.ts
  packages/happy-css-modules/src/emitter/source-map.ts
  packages/happy-css-modules/src/locator/index.ts
  packages/happy-css-modules/src/resolver/index.ts
  packages/happy-css-modules/src/resolver/webpack-resolver.ts
  packages/happy-css-modules/src/runner.test.ts
  packages/happy-css-modules/src/runner.ts
  packages/happy-css-modules/src/test-util/jest/resolver.cjs
  packages/happy-css-modules/src/test-util/tsserver.ts
  packages/happy-css-modules/src/test-util/util.ts
  packages/happy-css-modules/src/transformer/index.ts
  packages/happy-css-modules/src/transformer/less-transformer.ts
  packages/happy-css-modules/src/transformer/postcss-transformer.ts
  packages/happy-css-modules/src/util.ts
  packages/stylelint-happy-css-modules/src/rules/no-unused-selectors.ts
Labels: Type: Refactoring

#242 Implement TypeScript plugin
  package-lock.json
  package.json
  packages/example/.vscode/settings.json
  packages/example/07-typescript-plugin/Card.tsx
  packages/example/package.json
  packages/example/tsconfig.json
  packages/typescript-happy-css-modules-plugin/package.json
  packages/typescript-happy-css-modules-plugin/src/index.cts
  packages/typescript-happy-css-modules-plugin/tsconfig.build.json
  tsconfig.json
Labels: Type: Feature

#243 [typescript-plugin] Support `styleFileExtension` and `exportedStylesName` options
  packages/example/tsconfig.json
  packages/typescript-happy-css-modules-plugin/src/ast.cts
  packages/typescript-happy-css-modules-plugin/src/config.cts
  packages/typescript-happy-css-modules-plugin/src/index.cts
  packages/typescript-happy-css-modules-plugin/src/source.cts
Labels: Type: Feature

#244 Update devDependencies
  package-lock.json
  package.json
  packages/happy-css-modules/src/emitter/dts.ts
  packages/stylelint-happy-css-modules/package.json
Labels: Type: Dependencies

#246 [happy-css-modules] Require Node.js 18+
  .github/workflows/ci-node.yml
  package-lock.json
  package.json
  packages/happy-css-modules/package.json
  packages/stylelint-happy-css-modules/package.json
Labels: Type: Breaking Change

#245 [happy-css-modules] Update dependencies
  package-lock.json
  packages/happy-css-modules/package.json
  packages/happy-css-modules/src/integration-test/go-to-definition.test.ts
  packages/happy-css-modules/src/resolver/node-resolver.ts
  packages/happy-css-modules/src/resolver/webpack-resolver.ts
  packages/happy-css-modules/src/runner.test.ts
  packages/happy-css-modules/src/runner.ts
  packages/happy-css-modules/src/test-util/tsserver.ts
  packages/happy-css-modules/src/util.ts
  patches/postcss-load-config+4.0.1.dev.patch
Labels: Type: Dependencies

#247 Fix README
  packages/happy-css-modules/README.md
Labels: Type: Documentation

#249 Require `sass@1.63.3+`
  packages/happy-css-modules/package.json
  packages/happy-css-modules/src/transformer/scss-transformer.ts
Labels: Type: Change

#248 Update release note template
  .github/release.yml
Labels: Type: Other

#251 Tokens loaded by `composes` are not exported
  packages/example/03-composes/1.css.d.ts
  packages/example/03-composes/1.css.d.ts.map
  packages/example/03-composes/2.css.d.ts
  packages/example/03-composes/2.css.d.ts.map
  packages/example/04-sass/1.scss.d.ts
  packages/example/04-sass/1.scss.d.ts.map
  packages/example/05-less/1.less.d.ts
  packages/example/05-less/1.less.d.ts.map
  packages/example/app.ts
  packages/happy-css-modules/src/integration-test/go-to-definition.test.ts
  packages/happy-css-modules/src/locator/index.test.ts
  packages/happy-css-modules/src/locator/index.ts
  packages/happy-css-modules/src/locator/postcss.test.ts
  packages/happy-css-modules/src/locator/postcss.ts
  packages/happy-css-modules/src/test-util/util.ts
  packages/happy-css-modules/src/transformer/less-transformer.test.ts
  packages/happy-css-modules/src/transformer/scss-transformer.test.ts
Labels: Type: Fix

#253 Fix failing tests
  packages/happy-css-modules/src/locator/index.test.ts
Labels: Type: Other

#254 fix: watch mode not working on Windows
  packages/happy-css-modules/src/util.ts
Labels: Type: Fix

#257 Add RFC template
  designs/0000-template.md
Labels: Type: Other

#258 RFC: Philosophy
  designs/0001-philosophy.md
Labels: Type: Other

#259 Strict Type Checking RFC
  designs/0002-strict-type-checking.md
  designs/0002-strict-type-checking/namex-export.png
Labels: Type: Other
