Repository mizdra/happy-css-modules, pull requests merged in 2024-06, with the labels that each got.

#261 RFC: Generate .d.ts files for AltCSS
  designs/0003-generate-d-ts-files-for-altcss.md
Labels: Type: Other

#260 fix available API link
  README.md
Labels: Type: Other

#265 Token has only one `originalLocation`
  README.md
  packages/happy-css-modules/src/emitter/dts.ts
  packages/happy-css-modules/src/emitter/index.test.ts
  packages/happy-css-modules/src/locator/index.test.ts
  packages/happy-css-modules/src/locator/index.ts
  packages/happy-css-modules/src/test-util/util.ts
  packages/happy-css-modules/src/transformer/less-transformer.test.ts
  packages/happy-css-modules/src/transformer/postcss-transformer.test.ts
  packages/happy-css-modules/src/transformer/scss-transformer.test.ts
Labels: Type: Change

#213 Support for `@value`
  packages/example/01-basic/1.css
  packages/example/01-basic/1.css.d.ts
  packages/example/01-basic/1.css.d.ts.map
  packages/example/08-value-from/1.css
  packages/example/08-value-from/1.css.d.ts
  packages/example/08-value-from/1.css.d.ts.map
  packages/example/08-value-from/2.css
  packages/example/08-value-from/2.css.d.ts
  packages/example/08-value-from/2.css.d.ts.map
  packages/example/08-value-from/3.css
  packages/example/08-value-from/3.css.d.ts
  packages/example/08-value-from/3.css.d.ts.map
  packages/example/app.ts
  packages/happy-css-modules/src/emitter/dts.test.ts
  packages/happy-css-modules/src/emitter/dts.ts
  packages/happy-css-modules/src/locator/index.test.ts
  packages/happy-css-modules/src/locator/index.ts
  packages/happy-css-modules/src/locator/postcss.test.ts
  packages/happy-css-modules/src/locator/postcss.ts
  packages/happy-css-modules/src/test-util/util.ts
Labels: Type: Add
